version: '3.3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=cat
      - POSTGRES_USER=cat
      - POSTGRES_PASSWORD=cat
    expose:
      - '5432'
    ports:
      - '5432:5432'
  app:
    image: "guilhermecsbatista/the-cat-backend"
    environment:
      - SPRING_DATASOURCE_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"